/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AP
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
         setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newStudent = new javax.swing.JButton();
        newbook = new javax.swing.JButton();
        statistics = new javax.swing.JButton();
        issuebook = new javax.swing.JButton();
        returnbook = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newStudent.setBackground(new java.awt.Color(255, 255, 204));
        newStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/member-add-on-300x300.png"))); // NOI18N
        newStudent.setText("New Student");
        newStudent.setPreferredSize(new java.awt.Dimension(159, 59));
        newStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentActionPerformed(evt);
            }
        });
        getContentPane().add(newStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, -1));

        newbook.setBackground(new java.awt.Color(255, 255, 204));
        newbook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New book.png"))); // NOI18N
        newbook.setText("New Book");
        newbook.setPreferredSize(new java.awt.Dimension(159, 59));
        newbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbookActionPerformed(evt);
            }
        });
        getContentPane().add(newbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        statistics.setBackground(new java.awt.Color(255, 255, 204));
        statistics.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Statics.png"))); // NOI18N
        statistics.setText("Statistics");
        statistics.setPreferredSize(new java.awt.Dimension(159, 59));
        statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsActionPerformed(evt);
            }
        });
        getContentPane().add(statistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        issuebook.setBackground(new java.awt.Color(255, 255, 204));
        issuebook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issuebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/issue book.png"))); // NOI18N
        issuebook.setText("Issue Book");
        issuebook.setPreferredSize(new java.awt.Dimension(159, 59));
        issuebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebookActionPerformed(evt);
            }
        });
        getContentPane().add(issuebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        returnbook.setBackground(new java.awt.Color(255, 255, 204));
        returnbook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/return book png.png"))); // NOI18N
        returnbook.setText("Return Book");
        returnbook.setPreferredSize(new java.awt.Dimension(159, 59));
        returnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbookActionPerformed(evt);
            }
        });
        getContentPane().add(returnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        logout.setBackground(new java.awt.Color(255, 255, 204));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        logout.setText("LogOut");
        logout.setPreferredSize(new java.awt.Dimension(159, 59));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_Book_532388_1366x768.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentActionPerformed
        new NewStudent().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_newStudentActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
         setVisible(false);
        new login().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void newbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbookActionPerformed
        new NewBook().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_newbookActionPerformed

    private void issuebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebookActionPerformed
            new IssueBook().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_issuebookActionPerformed

    private void returnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbookActionPerformed
        new ReturnBook().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_returnbookActionPerformed

    private void statisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsActionPerformed
        new Statistics().setVisible(true);
    }//GEN-LAST:event_statisticsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton issuebook;
    private javax.swing.JButton logout;
    private javax.swing.JButton newStudent;
    private javax.swing.JButton newbook;
    private javax.swing.JButton returnbook;
    private javax.swing.JButton statistics;
    // End of variables declaration//GEN-END:variables
}
