/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AP
 */
import java.sql.*;
import Connection.DBConnection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bid = new javax.swing.JLabel();
        sid = new javax.swing.JLabel();
        issuedate = new javax.swing.JLabel();
        duedate = new javax.swing.JLabel();
        issue = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        bidfield = new javax.swing.JTextField();
        sidfield = new javax.swing.JTextField();
        issuefiled = new com.toedter.calendar.JDateChooser();
        duedatefiled = new com.toedter.calendar.JDateChooser();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bid.setText("Book ID");
        getContentPane().add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 60, 30));

        sid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sid.setText("Student ID");
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 158, 29));

        issuedate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issuedate.setText("Issue Date");
        getContentPane().add(issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 140, 30));

        duedate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        duedate.setText("Due Date");
        getContentPane().add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 140, 26));

        issue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/issue.png"))); // NOI18N
        issue.setText("Issue");
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });
        getContentPane().add(issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 279, 129, -1));

        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red-x-mark-transparent-background-3.png"))); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 279, 109, 57));

        bidfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(bidfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 94, 259, 30));

        sidfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(sidfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 136, 259, 28));
        getContentPane().add(issuefiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 176, 264, 30));
        getContentPane().add(duedatefiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 213, 264, 26));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed
        SimpleDateFormat dFormat=new  SimpleDateFormat("dd-MM-yyyy");
        String bookid=bidfield.getText();
        String studentid=sidfield.getText();
        String issueDate=dFormat.format(issuefiled.getDate());
        String dueDate=dFormat.format(duedatefiled.getDate());
        String returnBook="No";
        try{
        Connection con=DBConnection.getCon();
         String query="select * from Book where b_id='"+bookid+"'";
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery(query);
        if(rs.next())
        {
           ResultSet rs1=st.executeQuery("select * from Student where stud_id='"+studentid+"'");
           if(rs1.next())
           {
               st.executeUpdate("insert into Issue values('"+bookid+"','"+studentid+"','"+issueDate+"','"+dueDate+"','"+returnBook+"')");
               JOptionPane.showConfirmDialog(null,"Book Successfully Issued");
               setVisible(false);
               new IssueBook().setVisible(true);
           }
           else{
               JOptionPane.showConfirmDialog(null,"Incorrect student ID");
           }
        }
        else{
            JOptionPane.showConfirmDialog(null,"Incorrect BookID");
        }
       
        }
        catch(Exception e){
        JOptionPane.showConfirmDialog(null,"Connection error");}
// TODO add your handling code here:
    }//GEN-LAST:event_issueActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
            setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bid;
    private javax.swing.JTextField bidfield;
    private javax.swing.JButton clear;
    private javax.swing.JLabel duedate;
    private com.toedter.calendar.JDateChooser duedatefiled;
    private javax.swing.JButton issue;
    private javax.swing.JLabel issuedate;
    private com.toedter.calendar.JDateChooser issuefiled;
    private javax.swing.JLabel sid;
    private javax.swing.JTextField sidfield;
    // End of variables declaration//GEN-END:variables
}
