/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AP
 */
import java.sql.*;
import Connection.DBConnection;
import javax.swing.JOptionPane;
public class NewBook extends javax.swing.JFrame {

    /**
     * Creates new form NewBook
     */
    public NewBook() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bid = new javax.swing.JLabel();
        bname = new javax.swing.JLabel();
        publisher = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        publisheryear = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        bidfield = new javax.swing.JTextField();
        bnamefield = new javax.swing.JTextField();
        publisherfield = new javax.swing.JTextField();
        pricefield = new javax.swing.JTextField();
        publisheryearfield = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bid.setBackground(new java.awt.Color(255, 255, 204));
        bid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bid.setText("Book ID");
        getContentPane().add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 100, 25));

        bname.setBackground(new java.awt.Color(255, 255, 204));
        bname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bname.setText("Name");
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 136, 89, 28));

        publisher.setBackground(new java.awt.Color(255, 255, 204));
        publisher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        publisher.setText("Publisher");
        getContentPane().add(publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 205, 78, 27));

        Price.setBackground(new java.awt.Color(255, 255, 204));
        Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Price.setText("Price");
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 250, 100, 30));

        publisheryear.setBackground(new java.awt.Color(255, 255, 204));
        publisheryear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        publisheryear.setText("Publisher Year");
        getContentPane().add(publisheryear, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 298, 100, 26));

        save.setBackground(new java.awt.Color(255, 255, 204));
        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon--1.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 352, 121, 52));

        clear.setBackground(new java.awt.Color(255, 255, 204));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red-x-mark-transparent-background-3.png"))); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 352, 113, 52));

        bidfield.setBackground(new java.awt.Color(255, 255, 204));
        bidfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bidfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidfieldActionPerformed(evt);
            }
        });
        getContentPane().add(bidfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 90, 290, -1));

        bnamefield.setBackground(new java.awt.Color(255, 255, 204));
        bnamefield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(bnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 137, 290, -1));

        publisherfield.setBackground(new java.awt.Color(255, 255, 204));
        publisherfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(publisherfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 202, 290, -1));

        pricefield.setBackground(new java.awt.Color(255, 255, 204));
        pricefield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(pricefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 250, 290, -1));

        publisheryearfield.setBackground(new java.awt.Color(255, 255, 204));
        publisheryearfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(publisheryearfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 298, 288, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidfieldActionPerformed

    private void bnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnamefieldActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
            setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String bookid =bidfield.getText(); 
        String bookname=bnamefield.getText();
        String publisher=publisherfield.getText();
        String price=pricefield.getText();
        String publisheryear=publisheryearfield.getText();
        try{
         Connection con=DBConnection.getCon();
         Statement st=con.createStatement();
         String query="insert into Book values('"+bookid+"','"+bookname+"','"+publisher+"','"+price+"','"+publisheryear+"')";
         st.executeUpdate(query);
        JOptionPane.showMessageDialog(null,"Successfully Updated");
        setVisible(false);
        new NewBook().setVisible(true);
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,"Book Id is alredy Existed ");
        setVisible(false);
        new NewStudent().setVisible(true);
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Price;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bid;
    private javax.swing.JTextField bidfield;
    private javax.swing.JLabel bname;
    private javax.swing.JTextField bnamefield;
    private javax.swing.JButton clear;
    private javax.swing.JTextField pricefield;
    private javax.swing.JLabel publisher;
    private javax.swing.JTextField publisherfield;
    private javax.swing.JLabel publisheryear;
    private javax.swing.JTextField publisheryearfield;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
