/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AP
 */
import java.sql.*;
import Connection.DBConnection;
import javax.swing.JOptionPane;
public class NewStudent extends javax.swing.JFrame {

    /**
     * Creates new form NewStudent
     */
    public NewStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentid = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        fathername = new javax.swing.JLabel();
        coursename = new javax.swing.JLabel();
        branchname = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        close = new javax.swing.JButton();
        cname = new javax.swing.JComboBox<>();
        bname = new javax.swing.JComboBox<>();
        stdid = new javax.swing.JTextField();
        stdname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentid.setBackground(new java.awt.Color(255, 255, 204));
        studentid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentid.setText("Student ID");
        getContentPane().add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, 30));

        name.setBackground(new java.awt.Color(255, 255, 204));
        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 110, 30));

        fathername.setBackground(new java.awt.Color(255, 255, 204));
        fathername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fathername.setText("Father Name");
        getContentPane().add(fathername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 110, 30));

        coursename.setBackground(new java.awt.Color(255, 255, 204));
        coursename.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coursename.setText("Course Name");
        getContentPane().add(coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 110, 30));

        branchname.setBackground(new java.awt.Color(255, 255, 204));
        branchname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        branchname.setText("Branch Name");
        getContentPane().add(branchname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 110, 30));

        save.setBackground(new java.awt.Color(255, 255, 204));
        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon--1.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 150, 50));

        close.setBackground(new java.awt.Color(255, 255, 204));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red-x-mark-transparent-background-3.png"))); // NOI18N
        close.setText("Clear");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 150, 50));

        cname.setBackground(new java.awt.Color(255, 255, 204));
        cname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Tech", " " }));
        cname.setPreferredSize(new java.awt.Dimension(60, 120));
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 390, 30));

        bname.setBackground(new java.awt.Color(255, 255, 204));
        bname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "IT", "E&TC", "Civil", "MECH", "Elec" }));
        bname.setPreferredSize(new java.awt.Dimension(60, 120));
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 390, 30));

        stdid.setBackground(new java.awt.Color(255, 255, 204));
        stdid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stdid.setPreferredSize(new java.awt.Dimension(60, 120));
        getContentPane().add(stdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 390, 30));

        stdname.setBackground(new java.awt.Color(255, 255, 204));
        stdname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stdname.setPreferredSize(new java.awt.Dimension(60, 120));
        getContentPane().add(stdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 390, 30));

        fname.setBackground(new java.awt.Color(255, 255, 204));
        fname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fname.setPreferredSize(new java.awt.Dimension(60, 120));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 390, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String studentid =stdid.getText(); 
        String name=stdname.getText();
        String fathername=fname.getText();
        String coursename=(String)cname.getSelectedItem();
        String branchname=(String)bname.getSelectedItem();
        try{
         Connection con=DBConnection.getCon();
         Statement st=con.createStatement();
         st.executeUpdate("insert into Student values('"+studentid+"','"+name+"','"+fathername+"','"+coursename+"','"+branchname+"')");
        JOptionPane.showMessageDialog(null,"Successfully Updated");
        setVisible(false);
        new NewStudent().setVisible(true);
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,"Student Id is alredy Existed ");
        setVisible(false);
        new NewStudent().setVisible(true);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> bname;
    private javax.swing.JLabel branchname;
    private javax.swing.JButton close;
    private javax.swing.JComboBox<String> cname;
    private javax.swing.JLabel coursename;
    private javax.swing.JLabel fathername;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel name;
    private javax.swing.JButton save;
    private javax.swing.JTextField stdid;
    private javax.swing.JTextField stdname;
    private javax.swing.JLabel studentid;
    // End of variables declaration//GEN-END:variables
}
