/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AP
 */
import java.sql.*;
import Connection.DBConnection;
import javax.swing.JOptionPane;
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        bid = new javax.swing.JLabel();
        sid = new javax.swing.JLabel();
        issuedate = new javax.swing.JLabel();
        duedate = new javax.swing.JLabel();
        bidfield = new javax.swing.JTextField();
        sidfield = new javax.swing.JTextField();
        returnb = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        search = new javax.swing.JButton();
        issuedatefield = new javax.swing.JTextField();
        duedatefield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bid.setBackground(new java.awt.Color(255, 255, 204));
        bid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bid.setText("Book ID");
        getContentPane().add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 80, 92, -1));

        sid.setBackground(new java.awt.Color(255, 255, 204));
        sid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sid.setText("Student ID");
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 137, 84, -1));

        issuedate.setBackground(new java.awt.Color(255, 255, 204));
        issuedate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issuedate.setText("Issue Date");
        getContentPane().add(issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 194, 100, -1));

        duedate.setBackground(new java.awt.Color(255, 255, 204));
        duedate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        duedate.setText("Due Date");
        getContentPane().add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 253, 68, -1));

        bidfield.setBackground(new java.awt.Color(255, 255, 204));
        bidfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(bidfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 77, 276, -1));

        sidfield.setBackground(new java.awt.Color(255, 255, 204));
        sidfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(sidfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 134, 276, -1));

        returnb.setBackground(new java.awt.Color(255, 255, 204));
        returnb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        returnb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/return book png.png"))); // NOI18N
        returnb.setText("Return");
        returnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbActionPerformed(evt);
            }
        });
        getContentPane().add(returnb, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 304, -1, 39));

        clear.setBackground(new java.awt.Color(255, 255, 204));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red-x-mark-transparent-background-3.png"))); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 304, 100, 39));

        search.setBackground(new java.awt.Color(255, 255, 204));
        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 132, 120, 31));

        issuedatefield.setBackground(new java.awt.Color(255, 255, 204));
        issuedatefield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issuedatefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedatefieldActionPerformed(evt);
            }
        });
        getContentPane().add(issuedatefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 270, -1));

        duedatefield.setBackground(new java.awt.Color(255, 255, 204));
        duedatefield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(duedatefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 257, 276, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbActionPerformed
           String bookID=bidfield.getText();
            String studentID=sidfield.getText();
            try{
                Connection con=DBConnection.getCon();
                Statement st=con.createStatement();
                st.executeUpdate("update Issue set return_book='YES' where stud_id='"+studentID+"' and book_id='"+bookID+"'");
                JOptionPane.showMessageDialog(null,"Book Successfully Returned");
                setVisible(false);
                new ReturnBook().setVisible(true);
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Connection Error");
            }
    }//GEN-LAST:event_returnbActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String bookID=bidfield.getText();
            String studentID=sidfield.getText();
            try{
                Connection con=DBConnection.getCon();
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select * from Issue where book_id='"+bookID+"' and stud_id='"+studentID+"'");
                if(rs.next())
                {
                    issuedatefield.setText(rs.getString(3));
                    duedatefield.setText(rs.getString(4));
                    bidfield.setEditable(false);
                    sidfield.setEditable(false);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Books is not issued to this student");
                    setVisible(false);
                    new ReturnBook().setVisible(true);
                }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Connection Error");
            }// T
    }//GEN-LAST:event_searchActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
            setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void issuedatefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedatefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issuedatefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bid;
    private javax.swing.JTextField bidfield;
    private javax.swing.JButton clear;
    private javax.swing.JLabel duedate;
    private javax.swing.JTextField duedatefield;
    private javax.swing.JLabel issuedate;
    private javax.swing.JTextField issuedatefield;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton returnb;
    private javax.swing.JButton search;
    private javax.swing.JLabel sid;
    private javax.swing.JTextField sidfield;
    // End of variables declaration//GEN-END:variables
}
